version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "0.0.0.0:5341:80"
    networks:
      - wa-network

  Warptec.Docker.WebApi:
    image: warptec/webapi
    container_name: identity-api
    build:
      context: .
      dockerfile: Warptec.Docker.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44312    
      - ASPNETCORE_Kestrel__Certificates__Default__Password=0000
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/warptec-docker.com.pfx
      - PATH_BASE=/identity-api
    ports:
      - "0.0.0.0:44318:80"
      - "0.0.0.0:44312:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - wa-network

  auth-db:
    image: postgres:9.6
    container_name: auth-db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - auth-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  auth-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: auth-search
    environment:
      - cluster.name=fusionauth
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - auth-search
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    container_name: auth-fusionauth
    depends_on:
      - auth-db
      - auth-search
    environment:
      DATABASE_URL: jdbc:postgresql://auth-db:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_SERVERS: http://auth-search:9200
      FUSIONAUTH_URL: http://fusionauth:9011
      VIRTUAL_HOST: auth.warptec-docker.com
      VIRTUAL_PORT: 9011
    networks:
      - auth-db
      - auth-search
      - wa-network
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - fa_config:/usr/local/fusionauth/config

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: auth-proxy
    networks:
      - auth-db
      - auth-search
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${APPDATA}/apps/docker-articles/nginx/certs:/etc/nginx/certs
    
networks:
  wa-network:
    driver: bridge
  auth-db:
    driver: bridge
  auth-search:
    driver: bridge
    
volumes:
  db_data:
  es_data:
  fa_config: